notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

sudo: required

matrix:
  include:
    - os: linux
      python: 3.6
      env:
        - PYTHON_VERSION=3.6
    - os: linux
      python: 3.7
      env:
        - PYTHON_VERSION=3.7

before_install:
  - export PYTHONIOENCODING=UTF8
  - export MPLBACKEND=Agg

  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - . $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda  # get latest conda version
  - conda info -a # Useful for debugging any issues with conda

  - conda create --name cta-dev python=$PYTHON_VERSION pip numpy packaging
  - source activate cta-dev
  - pip install pytest

  # ----- target_software
  - conda install -c conda-forge cfitsio
  - conda install swig
  - mkdir -p $HOME/Software
  - cd $HOME/Software
  - git clone https://github.com/watsonjj/target_software.git
  - cd $TARGET_SOFTWARE
  - ./install.sh
  - cd $TRAVIS_BUILD_DIR
  # ----- end of target_software

  - conda install -c cta-observatory ctapipe

install:
- python setup.py develop

script:
- cd $TRAVIS_BUILD_DIR
- pytest -vvs
